<a href="https://colab.research.google.com/github/betty6you/Jing_INFO5731_Spring2020/blob/main/In_class_exercise_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **The second In-class-exercise (1/27/2021, 20 points in total)**


(1) Write a Python program to find the duplicate elements in a given array of integers. Return -1 If there are no such elements. (4 points)

In [201]:
# write your answer here
 
#Searches for duplicate element 
def array_duplicate_search(arr):

  for i in range(0, len(arr)):     
    for j in range(i+1, len(arr)):    
        if (arr[i] == arr[j]):    
            print("Duplicate elements in given array: "+str(arr[j])); 
            
        else:
          j=j+1

  return -1

array_duplicate_search([1, 2, 3, 4, 4, 5, 2] )
array_duplicate_search([1, 2, 3, 4] )

Duplicate elements in given array: 2
Duplicate elements in given array: 4


-1

(2) Write a Python program to select all the Sundays of a specified year. (4 points)



In [199]:
# write your answer here
from datetime import date, timedelta

def all_sundays(year):
# January 1st of the given year
       firstday = date(year, 1, 1)
# First Sunday of the given year       
       firstday += timedelta(days = 6 - firstday.weekday())  
       while firstday.year == year:
          yield firstday
          firstday += timedelta(days = 7)
          
for s in all_sundays(2008):
   print(s)

2008-01-06
2008-01-13
2008-01-20
2008-01-27
2008-02-03
2008-02-10
2008-02-17
2008-02-24
2008-03-02
2008-03-09
2008-03-16
2008-03-23
2008-03-30
2008-04-06
2008-04-13
2008-04-20
2008-04-27
2008-05-04
2008-05-11
2008-05-18
2008-05-25
2008-06-01
2008-06-08
2008-06-15
2008-06-22
2008-06-29
2008-07-06
2008-07-13
2008-07-20
2008-07-27
2008-08-03
2008-08-10
2008-08-17
2008-08-24
2008-08-31
2008-09-07
2008-09-14
2008-09-21
2008-09-28
2008-10-05
2008-10-12
2008-10-19
2008-10-26
2008-11-02
2008-11-09
2008-11-16
2008-11-23
2008-11-30
2008-12-07
2008-12-14
2008-12-21
2008-12-28


(3) Python files reading and writing. Download the “[exercise_02_data _collection.zip](https://github.com/unt-iialab/info5731_spring2021/blob/main/class_exercises/exercise_02_data_collection.zip)” to your local and un-zip it.

*   Write a program to read all the txt files and save the sentences in all the files into one csv file with two columns, the first column is sentence id (txt file name+sentence line number), the second column is the sentence text content. (4 points)
*   Remove all the punctuations from the sentences, save the processed sentences into a new column in the same csv file. (4 points)
*   Ask the user to enter a word, return all the sentences that include this word, three kinds of information should be returned: sentence id, sentence text content, the count that user input word appear in the sentence. (4 points)



In [174]:
import csv
with open("/content/In_class_exercise_02/ARTHROTEC.1.txt","r") as input_files:
  all_line=input_files.readlines()
  print(all_line)
  print(len(all_line))
fields=['Sentence ID', 'Sentence content']
rows=[input_files.name+str(len(all_line)), all_line]
with open("combine.csv","w") as out_files:
  csvwriter = csv.writer(out_files,delimiter='\t',)
  csvwriter.writerow(fields)
  csvwriter.writerow(rows)

out_files.close()

['I feel a bit drowsy & have a little blurred vision, so far no gastric problems.\n', "I've been on Arthrotec 50 for over 10 years on and off, only taking it when I needed it.\n", "Due to my arthritis getting progressively worse, to the point where I am in tears with the agony, gp's started me on 75 twice a day and I have to take it.\n", 'every day for the next month to see how I get on, here goes.\n', "So far its been very good, pains almost gone, but I feel a bit weird, didn't have that when on 50."]
5


In [187]:
import requests
import csv
for i in range(1,100):
  url = 'https://raw.githubusercontent.com/betty6you/Jing_INFO5731_Spring2020/main/exercise_02_data_collection/ARTHROTEC.'+str(i)+'.txt'
  response = requests.get(url)
  #count=len(response.text.readlines( ))
  #print(response.text)
  
  fields=['Sentence ID', 'Sentence content']
    rows= [url ,line]

  with open("Big.csv","w") as csvfile:
    csvwriter = csv.writer(csvfile,delimiter='\t',lineterminator='\n')
    csvwriter.writerow(fields)
    csvwriter.writerows(rows)



(4) Install packages nltk, numpy, scipy, pandas, and sklearn on Google Colab. Write a program to test whether they are installed successfully. (3 points for extra)

In [198]:
# write your answer here

!pip install nltk
import nltk
nltk.download('stopwords')

!pip install numpy
import numpy

cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]

C = numpy.array(cvalues)
print(C)
!pip install scipy
from scipy import constants

print(constants.liter)

!pip install pandas
import pandas
pandas.isnull(2)

!pip install sklearn
import sklearn
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()
print(digits.data)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]
0.001
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
